### PR TITLE
Extract kernel-doc comments for things besides functions

### LINKED ISSUE #134: Report kernel-doc for enum, struct, and #define
Forked off #78 per https://github.com/bootlin/elixir/issues/78#issuecomment-632611233 .

**Edit** while updating the parser, fix the missing docs at:
- https://elixir.bootlin.com/linux/v4.9.140/source/drivers/base/regmap/regmap.c#L2714
- https://elixir.bootlin.com/linux/v4.9.140/source/kernel/sched/completion.c#L111
- https://elixir.bootlin.com/linux/latest/ident/v4l2_fwnode_endpoint_parse (documented [here](https://elixir.bootlin.com/linux/latest/source/include/media/v4l2-fwnode.h#L216)) (as of v5.8.9)

### PR DESCRIPTION
**Pull request by cxw42**
Fixes #134.
- Add test files and test cases
- Look for kernel-doc comments on every symbol we get from our ctags invocations.  This includes at least structs, enums, and macros.
All tests pass on my system.

Happy Hacktoberfest to all! :)

### CODE REVIEW

**Comment by michaelopdenacker** [comment]
Accepted. Will test very soon. Many thanks!

**Comment by michaelopdenacker** [comment]
By the way, I get warnings when running the new code, to generate a new database
Use of uninitialized value $source_lines[0] in pattern match (m//) at /home/mike/github/elixir/find-file-doc-comments.pl line 118.

I let you have a look...
Cheers,
Michael

**Comment by cxw42** [comment]
@michaelopdenacker will do!  Can you give me any information about which file or blob triggers the warning?  I didn't see it on my system, which tells me I need to add a test case :) .

**Comment by michaelopdenacker** [comment]
Hi Chris
At this stage, I don't know. Here are more detailed logs, running `./utils/index-all-repositories`

```
linux - ids: v3.7: 41 new blobs (56.1%)
Use of uninitialized value $source_lines[0] in pattern match (m//) at /home/mike/github/elixir/find-file-doc-comments.pl line 118.
u-boot - refs: 120000 (85.0%)
Use of uninitialized value $source_lines[0] in pattern match (m//) at /home/mike/github/elixir/find-file-doc-comments.pl line 118.
linux - ids: v3.7.1: 18 new blobs (56.1%)
linux - vers: v2.6.35.6 done (46.5%)
Use of uninitialized value $source_lines[0] in pattern match (m//) at /home/mike/github/elixir/find-file-doc-comments.pl line 118.
Use of uninitialized value $source_lines[0] in pattern match (m//) at /home/mike/github/elixir/find-file-doc-comments.pl line 118.
linux - ids: v3.7.2: 124 new blobs (56.1%)
Use of uninitialized value $source_lines[0] in pattern match (m//) at /home/mike/github/elixir/find-file-doc-comments.pl line 118.
Use of uninitialized value $source_lines[0] in pattern match (m//) at /home/mike/github/elixir/find-file-doc-comments.pl line 118.
Use of uninitialized value $source_lines[0] in pattern match (m//) at /home/mike/github/elixir/find-file-doc-comments.pl line 118.
linux - vers: v2.6.35.7 done (46.5%)
linux - ids: v3.7.3: 215 new blobs (56.1%)
Use of uninitialized value in pattern match (m//) at /home/mike/github/elixir/find-file-doc-comments.pl line 118.
```
I just hoped you could guess what the error could be based on the code, but if you need me to add some instrumentation to debug this, I'll be happy to.
Cheers,
Michael

**Comment by cxw42** [comment]
@michaelopdenacker thanks - that was very helpful to narrow down my search!  I checked everything that changed from v3.7 to v3.8 and found a repro.  I opened #186 to track work on the fix.

**Pull request merged**
