### PR TITLE
Add basic automated-test suite

### PR DESCRIPTION
**Pull request by cxw42**
**Rationale:** I am working on doc-comment extraction (#78), and want to reduce the chance of breaking something by accident.  Also, @michaelopdenacker mentioned in https://github.com/bootlin/elixir/issues/87#issuecomment-580259149 that he was interested in using the command line to test Elixir.

**Therefore:** I propose this PR, which adds a basic automated test of update.py and query.py.  To run the tests, say `prove` in the top-level directory.  (`prove` comes with Perl, which Elixir already uses.)

This PR sets up infrastructure I can later use to test web.py and api.py without having to run a local Apache instance.  It does not include those specific tests --- it is just a starting point.

- For test data, I am using some GPL2+ files from Linux v5.4.  I picked the i2c tree and some headers it uses, just because I have been using i2c recently at $work.  Everything in `t/tree` is copied straight from the kernel.
  - Note on licensing: I believe these GPL2-or-later files can be included in this AGPL3+ project.  See b22a562 and the updated README for explanation and links.  (Note: I am not a lawyer, and this is not legal advice.  If you do not want to use these files, we can always pick a different C code base.)
- The test creates a git repo in /tmp, runs update.py, then runs a few query.py requests (both `file` and `ident`).  It currently leaves the database in `t/db` for inspection, but I would be happy to put that in `/tmp` also if you would prefer.

Thank you for considering this PR!  I look forward to your feedback.

### CODE REVIEW

**Comment by michaelopdenacker** [comment]
Hi Chris,
Many thanks for this pull request. I'll do my best to test it by the end of the week :)
Thanks again,
Cheers,
Michael

**Comment by michaelopdenacker** [comment]
Accepting this contribution so that others can test it too.
Many thanks Chris :)
Michael.

**Comment by michaelopdenacker** [comment]
Must say I'm impressed by the results. Very useful, many thanks again :)

**Comment by cxw42** [comment]
Glad to help!  I will now be able to add tests for the doc-comment extraction, and then send a PR with the tests and the code.  Thank you!

**Comment by michaelopdenacker** [comment]
Great, you're a true architect :)
Good luck!
Michael.

**Pull request merged**
