### PR TITLE
 Show a loading indicator if API fetch takes more than 200 milliseconds 

### PR DESCRIPTION
**Pull request by fstachura**
Some identifiers can take a really long time to load, depending, among other things, on quality of internet connection. This can result in a confusing situation, where clicking on an identifier seems to do nothing at all, until the popup loads after few seconds. I propose adding a loading indicator which will show up if the API fetch takes more than 200 milliseconds.

I have updated https://elixir.ksi.ii.uj.edu.pl with this branch + a change that adds a random delay to every api call, so that the loading indicator is often visible.

Note: this branch is based on https://github.com/bootlin/elixir/pull/267

### CODE REVIEW

**Comment by fstachura** [comment]
This is of course not related to the lack of compression on the api endpoint, as noticed by @tleb here https://github.com/bootlin/elixir/pull/265#issuecomment-1858003105

**Comment by tleb** [comment]
Any reason to wait 200ms? 100ms is the expected max time for user interactions. Else any reason not to display it immediately?

**Comment by fstachura** [comment]
> Any reason to wait 200ms? 100ms is the common value for max user input delay to feel instantaneous.
The value is completely arbitrary. I can reduce this to 100ms if you think it's a better value. 

> Else any reason not to display it immediately?
I suspect that for most cases the popup should load almost immediately, so I decided to add a delay to avoid the indicator flashing right before the expected content loads.

**Comment by michaelopdenacker** [comment]
Merged
and deployed on https://elixir.bootlin.com/
Many thanks!

**Pull request merged**
