### PR TITLE
Update docker files for Elixir 2.1

### PR DESCRIPTION
**Pull request by MaximeChretien**
Docker files needs to be updated to work properly with Elixir 2.1 since we have made a lot of changes since Elixir 1.0

/!\ This hasn't been tested

- [x] Update Debian dockerfile
- [x] Update Centos dockerfile
- [x] Test Debian docker
- [x] Test Centos docker

Related to https://github.com/bootlin/elixir/issues/172

### CODE REVIEW

**Comment by MaximeChretien** [comment]
For the centos one we will need to build a .rpm for universal-ctags I think, I don't really know how it works

Also, I see that we use port 80 in Debian and port 8080 in centos, I there a reason for that ?

**Comment by MaximeChretien** [comment]
The debian dockerfile is working fine for me now.

For the centos one, I think we will use a snap package for universal-ctags, there is no universal-ctags rpm package already existing apparently, so it will be easier to use the already existing snap package and update it for the last version.

And a snap package will allow people to use our version of universal-ctags in other distributions.

**Comment by MaximeChretien** [comment]
Well it looks like snap can't be used in docker images because of some problems with systemd and dbus ...

Any ideas about what we could do to update the centos dockerfile ?

It looks like openSUSE Tumbleweed has rpm packages for universal-ctags, maybe I can use that to create an updated rpm.

Or maybe universal-ctags will need to be built from source while creating the docker container.

**Comment by MaximeChretien** [comment]
Everything is working fine for me (at least with Toybox).

For universal-ctags in centos I built an rpm package.

I currently doing some tests with U-Boot to be sure everything is fine.

@michaelopdenacker You need to add the rpm file I sent you before merging this.

**Comment by michaelopdenacker** [comment]
Accepted, many thanks!
Michael.

**Pull request merged**
