### PR TITLE
Extract doc comments - back-end

### PR DESCRIPTION
**Pull request by cxw42**
(I will rebase this after some of the other open PRs are merged, but I wanted to post it now to provide an opportunity for feedback.)

This PR adds back-end support for doc-comment extraction (part of #78).  It does not update api.py or web.py.

### Notes on some specific points

While reading through the existing Python code, I found a number of the variable names confusing.  For example, in update.py, "blob" isn't a hash; it's a sequential ID that maps to a blob in a particular tag.  I changed some of the variable names to try to reduce confusion for myself and for future readers :) .  I can certainly change them back and add comments if you wish.

In query.py, subcommand `ident` has a loop over blobs to collect all the defs and refs.  I needed to add doc comments to that loop, and took advantage of the opportunity to express the logic in a way I believe is more clear.  Again, feel free to disagree --- comments welcome!

### Overview of changes

- find-file-doc-comments.pl: new script that finds doc comments in a source file
- data.py: Add database to store doc-comment locations
- script.sh: Add parse-docs subcommand
- update.py:
  - Add code to process doc comments
  - Update some variable names in hopes of reducing confusion
- query.py:
  - Add code to report doc comments
  - Update some variable names in hopes of reducing confusion

Also:
- t/TestEnvironment.pm: Add find_doc attribute
- t/interact.pl: Don't die if update.py fails
- t/TestHelpers.pm: Permit checking specific sections of query.py output
- t/300: update regexes per the preceding
- gitignore tags (`ctags -R` output)

### CODE REVIEW

**Comment by michaelopdenacker** [comment]
Hi Chris,
Thanks for the commenting and symbol renaming work. I agree it makes the code easier to understand.
Can you take care of rebasing this PR so that I can merge and then test it?
I'll build a new database and will switch to it on the production server (and the newest version of Elixir) if everything is all right. Otherwise, we can still fix issues in future commits.
Thanks for all your work :)
Cheers,
Michael.

**Comment by cxw42** [comment]
@michaelopdenacker Rebased!  And I see you got Travis set up :D .  Note that this back-end only extracts doc for functions at the moment --- I will add other symbols in the future.

@carmeli-tamir Would you please take a look at the Python errors in the [log](https://travis-ci.com/github/bootlin/elixir/builds/157984537) and see if you have any ideas?  I think I can fix the "too many values to unpack," but I'm not sure about the rest.

**Comment by michaelopdenacker** [comment]
Hi Chris,
Many thanks!
Did I manage to get Travid CI up? I thought I didn't yet... I'll check again.
Merging the PR. I should be able to test tomorrow.
Thanks again,
Michael.

**Comment by michaelopdenacker** [comment]
Hi Chris,
I hope you and your family are doing well..
Are you finding time to work on the front-end part?
The documentation data are now in the production database so we will be ready to switch when you're ready too.
I'm asking because we are going to make a 2.0 release in the next weeks, that will in particular support Kconfig parameters and DTS labels as identifiers. It would be great if we could have the documentation front-end at the same time too...
Take care,
Michael.

**Comment by cxw42** [comment]
Thanks for the update!  I am plugging away.  Do you have a hard date for the release yet?

**Comment by michaelopdenacker** [comment]
Hi Chris,
We should be ready by the beginning of next week, and will start updating the production site then. However, we could bump up the version to 1.99, and wait for your contribution a few more days (by the end of the week if possible) to make the 2.0 release and announce it.
I hope you can make it
Cheers,
Michael.

**Pull request merged**
