### PR TITLE
Refactored ident query to use python objects rather than parsing REs

### PR DESCRIPTION
**Pull request by carmeli-tamir**
Refactored for now only the ident command.

After this is approved we can go and change the other queries one by one to eliminate the regexes.
I might add some more documentation / small style fixes but you can already review it and comment so I could fix. 
Thanks!

### CODE REVIEW

**Comment by michaelopdenacker** [comment]
Tested that the web interface still works after this change.
However, the command line interface seems to be broken
Example with Linux:
> ./query.py ident v5.3.2 request_irq
Traceback (most recent call last):
  File "./query.py", line 144, in <module>
    sys.stdout.buffer.write (output)
TypeError: a bytes-like object is required, not 'tuple'

I could reproduce this with a much smaller project (easier to index)
Thanks for this effort!
Michael.

**Comment by michaelopdenacker** [comment]
Merged. @pokazef will take care of reviving the CLI after your changes.
Thanks :)

**Comment by pokazef** [comment]
OK, I'll get on it as soon as I can.

**Comment by michaelopdenacker** [comment]
Great. Count on me for testing! Thanks.

**Pull request merged**
