### PR TITLE
index-all-repositories : Fetch all tags

### PR DESCRIPTION
**Pull request by MaximeChretien**
This is needed for old linux versions

### CODE REVIEW

**Comment by cxw42** [comment]
I suggest also documenting that this requires Git 1.9+ - https://stackoverflow.com/a/20608181 .  Earlier gits needed separate branch and tag fetches, or two refspecs given on the command line.

**Comment by MaximeChretien** [comment]
@cxw42 Git 1.9 seems to be out since Feb 2014, I don't think someone is still using an older version of git ^^'

**Comment by cxw42** [comment]
Maybe not :) .  However, I actually ran into this problem once (fetch != fetch --tags on old git).  If documenting it takes you less time than it would take you to respond if someone opened an issue, why not write it up? ;)

**Comment by michaelopdenacker** [comment]
Accepted, thanks!

**Pull request merged**
