### PR TITLE
Straightened the interface between query and web, as preparation to a…

### PR DESCRIPTION
**Pull request by carmeli-tamir**
Straightened the interface between query and web, as preparation to add a json api parallel to web (above query):
1. 'versions' query now returns an object, in the format documented by @michaelopdenacker 
2. 'latest' query returns a string (not bytes)
3. 'type' query returns a string (not bytes)
4. 'dir' returns a list of strings matching the content of the dir (not a chunk of bytes)
5. 'file' query returns a string (not bytes)

If no special problems occur my next PR shall be the json interface - this is unless you want me to take care of the CLI interface, in which case I suggest to split query to different functions and have them called by argparse for the CLI. Tell me if you'd like me to take care of that too.

### CODE REVIEW

**Comment by michaelopdenacker** [comment]
Hi,
Many thanks for these new changes!

However, something seems to be broken, maybe with managing the latest versions...

In my test instance, http://lxrng/linux/v5.3.4/ident/kmalloc works (multiple results), but http://lxrng/linux/latest/ident/kmalloc just says "Identifier not used".

Sorry, the test machine is not publicly available (it's on a private network).

Any clue why this happens?

Thanks again,
Michael.

**Comment by michaelopdenacker** [comment]
Forget it, it's probably an issue with my database that is out of sync with the git repository. I'll check.

**Comment by michaelopdenacker** [comment]
I confirm that there is something wrong in this commit. It's not a mismatch between the git repository and database as I suspected.
Just reverting the patch, everything remaining the same, makes the issue go away.
I could investigate, but that should probably be easier for you...
Cheers,
Michael

**Comment by pokazef** [comment]
The problem is that query('latest') returns 'v5.3.4\n'.

The trailing newline used to be taken care of in web.py/call_query(), but obviously that interface has changed. The simplest fix for now is to just strip it in query(), but I still need to wrap my head around the changes before I can really clean this up.

**Pull request merged**
