### PR TITLE
Cancel a loading popup if another identificator is clicked

### PR DESCRIPTION
**Pull request by fstachura**
Fixes a bug, that sometimes causes confusing behavior if two identifiers are clicked, and the first identifier loads after the second one.

To reproduce:
1. Find a file that contains an identifier with a long list of references (good examples: `true`, `continue`, `switch`, although cache might cause the list of references to load too fast for this to work)
2. Click the identifier, and then, while the first identifier is still loading, click another one (preferably with a shorter list of references, so that the popup for the second identifier will load before the popup for the first identifier)

There is a high chance that the popup for the second identifier will load and then disappear to be replaced by a popup for the first identifier. This patch aims to fix that behavior.

I have deployed this patch on https://elixir.fbstc.org/

### CODE REVIEW

**Comment by michaelopdenacker** [comment]
@fstachura , @tleb : thanks for the patch and review. However, I severely lack time these days for testing. Shall I merge this now? We can still make further improvements later...
Thanks again

**Comment by fstachura** [comment]
> Ideally, requesting another popup would also abort the previous fetch(). See [MDN doc](https://developer.mozilla.org/en-US/docs/Web/API/AbortController/abort). I think a global AbortController passed to all fetch() calls should do it. Before starting a new fetch() we first abort all running fetches. Note: I've not checked a single AbortController can be passed to multiple fetch() and can be reused.

@tleb Good point, I will try to implement it today or tommorrow.

@michaelopdenacker I think it's better if I add AbortController support first

**Comment by fstachura** [comment]
Ok, AbortController support added.

**Comment by tleb** [comment]
Tested locally, can confirm it works as expected. Thanks @fstachura!

**Comment by michaelopdenacker** [comment]
Many thanks for the patch and reviews. Happy to merge the patch!

**Pull request merged**
