### PR TITLE
Add a mode that displays a popup on identifier click instead of redirecting to another URL

### PR DESCRIPTION
**Pull request by fstachura**
TODO:
- [x] - Test popup positioning

### CODE REVIEW

**Comment by michaelopdenacker** [comment]
Thanks, the result looks very nice.
Could you update your branch so that it is ready for merging. The Docker changes are already in and you should have only one (fixed) commit for the dynamic-references file.
Thanks in advance :)

**Comment by michaelopdenacker** [comment]
I have no issue on Firefox 119.0.1
Same for some of my colleagues on 120.0.1.
There's someone with an older version of Firefox (115.5.0esr) who has the issue too. So, if that's just on older versions of Firefox, I'm not sure we can do anything about it, and the problem will go away progressively as people update their browsers.

**Comment by tleb** [comment]
I think the issue is more with the viewport height than the browser used. Try dezooming and you should see the code block move vertically.

**Comment by fstachura** [comment]
Thanks for comments @tleb 

> With this patch & JS enabled, I don't see a way to reach the "old page". It is useful to get a copy-able link.

I'm not sure if I understand. I plan on hiding this option behind a checkbox, so the old, non-js version will be the default. Although having different links for both versions is also an option. 

>  On your instance and using Firefox, code rendering is broken. Code start is offset in some cases. See this [image](https://github.com/bootlin/elixir/assets/7550889/d17c3d92-54e4-4f83-8e48-9b50ea6ece40). It might not be linked to this series though?

I mentioned that in issue #264 and I'm pretty sure that its not related to the patch. Regarding browser versions - I use Firefox 120.0 and alignment is broken for me, too. I managed to fixed that once by manually editing HTML is inspector, I will try to create a patch for that too.

> It re-implements the rendering. Maybe using an iframe would be simpler?
  
I thought about it and I decided to render the contents in Javascript. I think that this should make the feature a little bit snappier (less bits send over the wire+something about browsing contexts), although I do admit that I just copied the old rendering code straight to JS, with as little changes as possible. Rendering this in JS also gives us more flexibility - I was initially planning to write new rendering code, but the old, ported code actually turned out to be good enough for the popup (IMO), so I left it as-is.
I don't see many advantages to using an iframe, except for code reuse, and even that is debatable because (I think?) we will have to create a new endpoint that renders just the popup contents.
    
> I don't know if Elixir has specific browsers it wants to support? I'm seeing async, fetch, etc. [Can I Use](https://caniuse.com/) says those are well supported, but I think the discussion should be had to be clear.

Good point! I'm not sure if Elixir has any browser support goals. I will try to research what is the oldest supported browser. What do you think @michaelopdenacker ?

**Comment by fstachura** [comment]
Adding class="highlight" to the div inside `<td class="code>` seems to fix the alignment issue. All that HTML seems to come from Pygments, and I don't know if Pygments API allows any control over it. Maybe production uses a different version of Pygments? Note that line numbers still look different from production.  

image

**Comment by fstachura** [comment]
> Why make the non-JS version the default? I think everyone will agree that your
implementation is the most sensible. Also, I'm not sure adding an option is
useful; I'd vote for keeping the tool as simple as possible. If people don't
want this feature, they can disable JS.

Yeah, maybe it's better to make it as simple as possible. I was thinking that maybe some people are used to the old workflow and would want an easy way to opt out. But maybe I'm overthinking it. Disabling Javascript definitely works. I don't insist on the checkbox, I actually would prefer to not implement it too, so if the consensus is that it's unnecessary, I won't implement it.

> Also, I'd be nice if this implementation didn't trigger on Ctrl+Click and let
the default browser behavior of opening in a new tab. That would fit my usecase
the best at least.

Good catch, should be fixed now. I also disabled it for meta (used instead of ctrl on macos) and shift (opens a new window in most browsers).

**Comment by michaelopdenacker** [comment]
> Thanks for comments @tleb
> 
> > With this patch & JS enabled, I don't see a way to reach the "old page". It is useful to get a copy-able link.
> 
> I'm not sure if I understand. I plan on hiding this option behind a checkbox, so the old, non-js version will be the default. Although having different links for both versions is also an option.
> 
> > On your instance and using Firefox, code rendering is broken. Code start is offset in some cases. See this [image](https://github.com/bootlin/elixir/assets/7550889/d17c3d92-54e4-4f83-8e48-9b50ea6ece40). It might not be linked to this series though?
> 
> I mentioned that in issue #264 and I'm pretty sure that its not related to the patch. Regarding browser versions - I use Firefox 120.0 and alignment is broken for me, too. I managed to fix that once by manually editing HTML in elements inspector, I will try to create a patch for that too.
> 
> > It re-implements the rendering. Maybe using an iframe would be simpler?
> 
> I thought about it and I decided to render the contents in Javascript. I think that this should make the feature a little bit snappier (less bits send over the wire+something about browsing contexts), although I do admit that I just copied the old rendering code straight to JS, with as little changes as possible. Rendering this in JS also gives us more flexibility - I was initially planning to write new rendering code, but the old, ported code actually turned out to be good enough for the popup (IMO), so I left it as-is. I don't see many advantages to using an iframe, except for code reuse, and even that is debatable because (I think?) we will have to create a new endpoint that renders just the popup contents.
> 
> > I don't know if Elixir has specific browsers it wants to support? I'm seeing async, fetch, etc. [Can I Use](https://caniuse.com/) says those are well supported, but I think the discussion should be had to be clear.
> 
> Good point! I'm not sure if Elixir has any browser support goals. I will try to research what % of browser market does not support this feature. What do you think @michaelopdenacker ?

Right, we don't have any specific browser support goals. We should be as standard as possible, and not require a specific browser. This been said, I guess Elixir should be compatible with both Firefox and Chromium, which AFAIK are the most popular ones in Linux kernel developers.

**Comment by michaelopdenacker** [comment]
> > > With this patch & JS enabled, I don't see a way to reach the "old page". It
> > > is useful to get a copy-able link.
> > 
> > 
> > I'm not sure if I understand. I plan on hiding this option behind a checkbox,
> > so the old, non-js version will be the default. Although having different links
> > for both versions is also an option.
> 
> Why make the non-JS version the default? I think everyone will agree that your implementation is the most sensible. Also, I'm not sure adding an option is useful; I'd vote for keeping the tool as simple as possible. If people don't want this feature, they can disable JS.
> 
> Also, I'd be nice if this implementation didn't trigger on Ctrl+Click and let the default browser behavior of opening in a new tab. That would fit my usecase the best at least.
> 
> > > It re-implements the rendering. Maybe using an iframe would be simpler?
> > 
> > 
> > I thought about it and I decided to render the contents in Javascript. I
> > think that this should make the feature a little bit snappier (less bits send
> > over the wire+something about browsing contexts), although I do admit that I
> > just copied the old rendering code straight to JS, with as little changes as
> > possible. Rendering this in JS also gives us more flexibility - I was initially
> > planning to write new rendering code, but the old, ported code actually turned
> > out to be good enough for the popup (IMO), so I left it as-is. I don't see many
> > advantages to using an iframe, except for code reuse, and even that is
> > debatable because (I think?) we will have to create a new endpoint that renders
> > just the popup contents.
> 
> It duplicates logic, meaning maintenance will be harder. I guess it's not a big code block & it does not have many chances of changing nowadays.
> 
> > Adding class="highlight" to the div inside `<td class="code">` seems to fix
> > the alignment issue. All that HTML seems to come from Pygments, and I don't
> > know if Pygments API allows any control over it. Maybe production uses a
> > different version of Pygments? Note that line numbers still look different from
> > production.
> 
> Indeed this comes from `pygments`. I don't have access to the server hosting Elixir so I'll let @michaelopdenacker answer. We should add a `requirements.txt` file to the project to make things more reproducible.

Here's what we have on https://elixir.bootlin.com/
python3-pygments                2.11.2+dfsg-2
We should be able to ask for a more recent version if necessary.

**Comment by michaelopdenacker** [comment]
> > Why make the non-JS version the default? I think everyone will agree that your
> > implementation is the most sensible. Also, I'm not sure adding an option is
> > useful; I'd vote for keeping the tool as simple as possible. If people don't
> > want this feature, they can disable JS.
> 
> Yeah, maybe it's better to make it as simple as possible. I was thinking that maybe some people are used to the old workflow and would want an easy way to opt out. But maybe I'm overthinking it. Disabling Javascript definitely works. I don't insist on the checkbox, I actually would prefer to not implement it too, so if the consensus is that it's unnecessary, I won't implement it.

I also vote for making the JS version the default one, and tell people who don't like it to disable Javascript for our website.
So OK to try and switch over! As long as we keep a way to disable it in case of trouble without having to remove the change.

**Comment by fstachura** [comment]
> Here's what we have on https://elixir.bootlin.com/
python3-pygments 2.11.2+dfsg-2
We should be able to ask for a more recent version if necessary.

Ok, turns out the alignment issue is my fault, related to the previous Dockerfile patch. I completely misunderstood how pipx works so Elixir was using a system-wide version of Pygments, not the custom version from https://bootlin.com/pub/elixir/. Sorry for that, I will submit a patch soon.

**Comment by fstachura** [comment]
Ok, I think I have finished all features/fixes that I thought are important. 

* Situations where the popup is (partially) outside of the viewport should happen less often now. 
* The popup should never obscure the identifier now. 
* I have also increased the popup width to 100% of the width of the viewport on mobile devices (or anything less wide than 900px). 
* The popup should now close on escape press.

**Comment by michaelopdenacker** [comment]
Hi
Thanks a lot for these updates!
Could you rebase this branch and merge the commits that can be merged (like commits fixing earlier commits in the branch)? This would definitely help in the review and presenting "clean" commits in the master branch.
This would be of great help as my available time is rather limited these days.
Thanks again
Cheers
Michael.

**Comment by fstachura** [comment]
I squashed all commits into a single commit, since most of them were fixes.

**Comment by michaelopdenacker** [comment]
Many thanks!
I'll try to merge it tomorrow morning (won't be able to intervene this afternoon in case of trouble)

**Comment by michaelopdenacker** [comment]
Merged, and now live on https://elixir.bootlin.com
Many thanks!!!

**Comment by tleb** [comment]
Follow-up to this: we don't appear to be compressing the API JSON responses on https://elixir.bootlin.com. See for example the `bool` ident that triggers a 1.95MB response that is not compressed.

**Comment by heatd** [comment]
Hil folks,

FYI, this feature seems to have broken Chrome (I'm on 119.0.6045.199).

Repro:
1) Open https://elixir.bootlin.com/linux/latest/source/include/linux/pipe_fs_i.h#L26 (this should place your file position on line 26)

2) Click pipe_inode_info

3) Observe brokenness on Chrome, correctness on Firefox

image

Notice how it doesn't create a nice window, it just randomly clips the file's viewport up at the top

image

Correct firefox viewing of the same steps

Thanks!

**Comment by fstachura** [comment]
Hi @heatd 

I had that happen to me once, I think it's related to the cache. Have you tried force refreshing the page (ctrl+f5) or clearing the browser cache?

**Comment by heatd** [comment]
> Hi @heatd
> 
> I had that happen to me once, I think it's related to the cache. Have you tried force refreshing the page (ctrl+f5) or clearing the browser cache?

Thanks @fstachura, that did the trick! I ctrl+f5'd and the issue went away. I guess something is wrong with your caching?

**Comment by fstachura** [comment]
> Thanks @fstachura, that did the trick! I ctrl+f5'd and the issue went away. I guess something is wrong with your caching?

Kind of, it most likely happens because I forgot to update the v parameter on stylesheet link. See https://github.com/bootlin/elixir/pull/267/files#diff-4d25ecf848b3aef11a6e80ba6a200937e2999e7699c735db7bccdc2a9d07c48eR9

**Pull request merged**
