### PR TITLE
Add travis ci

### PR DESCRIPTION
**Pull request by carmeli-tamir**
Hi,
Following @cxw42 work to write tests I think it's time to add a proper CI (continuous integration) as a merge check.
This will reduce the amount of manual work to check every PR, and will continue to reduce with every new added test.

@michaelopdenacker You will need to follow the first 3 steps [here](https://docs.travis-ci.com/user/tutorial/#to-get-started-with-travis-ci).

The CI's only action other than setting up the environment is running the "prove" command.

I have checked that the CI fails when there is a bug on the first commit and this [run](https://travis-ci.com/github/carmeli-tamir/elixir/builds/152280920), and CI success on the final success on this [run](https://travis-ci.com/github/carmeli-tamir/elixir/builds/152694714)

### CODE REVIEW

**Comment by cxw42** [comment]
Thanks - good idea!  The test coverage isn't very high at the moment :) , but a CI setup gives us incentive to add tests.  `prove` will run t/*.t, so the CI setup won't have to change when we add test files.

**Comment by michaelopdenacker** [comment]
Nice idea, but Mmm, why would Travis CI need write access to all my repositories ?

>>>
Repositories
Public and private

This application will be able to read and write all public and private repository data. This includes the following:

    Code
    Issues
    Pull requests
    Wikis
    Settings
    Webhooks and services
    Deploy keys
    Collaboration invites
<<<

Can I allow access to just one repository?
And why write access!?

Cheers,
Michael

**Comment by carmeli-tamir** [comment]
That's weird, I don't see write access to code on my account. Here's how the permissions look for me:
image

Also notice that I can select repository access. Probably you can do it only after authorization.
Linking to travis security [statement](https://docs.travis-ci.com/legal/security#how-does-travis-access-my-github-account), stating: 

> Under no circumstances does Travis CI write or modify source code or Git metadata in your GitHub repositories, source code from your repositories is accessed read-only for the sole purpose of automatically executing the tests or any other build commands requested.

At the end, it's your choice to make :)

**Comment by michaelopdenacker** [comment]
Accepting this change, which will allow me to test.
Many thanks :)
Michael.

**Comment by michaelopdenacker** [comment]
Mmm, I'm still stuck with this.

I tried to give TravisCI access to all my repositories, but the problem is I don't have any! 
I've been contributing to Elixir through https://github.com/bootlin/, which is an organization I own.

However, as an individual Github user, I don't own any! The organization I own does.
Is anyone familiar enough with Github and TravisCI to advise me how to enable TravisCI for one of the repositories my organization owns?

Thanks in advance,
Michael.

**Comment by carmeli-tamir** [comment]
It does seem a bit tricky.
From this [thread](https://github.com/travis-ci/travis-ci/issues/2519)
I suggest to try tiandavis's suggestion:

1) Publicize your membership in the organization following [these](https://help.github.com/en/github/setting-up-and-managing-your-github-user-account/publicizing-or-hiding-organization-membership) instructions

2) Sync account (I guess it's the Sync account) button on [this](https://travis-ci.com/account/repositories) page

**Comment by michaelopdenacker** [comment]
Hi Tamir
Thanks for the tips.
I made my organization membership visible and I synced, but that didn't help.
I'm going through the thread you suggested to find out more.
We'll find a way, other than cloning the repository on my own account :)
Michael.

**Comment by cxw42** [comment]
I was able to set up organization access for https://github.com/hopenbuild.  I also had to:
- grant organization access to Travis - https://github.com/settings/connections/applications/f244293c729d5066cf27 (Settings | Applications | Authorized OAuth Apps | "Travis CI for Open Source")
- On https://travis-ci.org/account/repositories:
  - hit Sync (travis-ci.**org**, not **com**)
  - refresh the page
  - Click on the name of the organization
  - Hit the toggle next to the repo

I just tried this with https://github.com/interpreters/perlpp, which I hadn't set up before:

image

Hope this helps!

**Pull request merged**
