### PR TITLE
autocomplete: Submit form on item selection

### PR DESCRIPTION
**Pull request by fstachura**

### CODE REVIEW

**Review by tleb — CHANGES_REQUESTED** [review]
Apart from that small comment, ACK.
What are the changes that were made to this custom version of the Autocomplete.JS lib (as mentioned in the top code comment)? Would updating to the latest version bring us interesting features or bug fixes?

**Comment by fstachura** [comment]
> What are the changes that were made to this custom version of the Autocomplete.JS lib (as mentioned in the top code comment)

I don't know, I would need to compare it with the original.

> Would updating to the latest version bring us interesting features or bug fixes?

I think we are on the latest version already. The domain from the comment seems to be dead, but I think I found the git repository: https://github.com/autocompletejs/autocomplete.js/blob/2.7/src/autocomplete.ts

**Comment by fstachura** [comment]
The project seems to be abandoned, and we are probably better of treating it as a part of Elixir (leaving the information about the original author in, of course)

**Comment by tleb** [comment]
Cherry picked into 9a27c7ae208e06715b276ceec0c50e5f5767aab5.

**Pull request closed without merging**
