### PR TITLE
Add optee support

### PR DESCRIPTION
**Pull request by mwalle**
Please note that I wasn't able to actually test it. But I've tested the list_tags_h() function, though.

### CODE REVIEW

**Comment by michaelopdenacker** [comment]
Adopted, it looks good so far. Many thanks!  
I'm merging it and I'll see what's missing (if any).
Thanks again. Good idea to add op-tee.
Michael.

**Comment by michaelopdenacker** [comment]
I published an update to the production website, but there are still issues with tags (they are not displayed in the menu)
I'll take care of that later... busy day!

**Comment by mwalle** [comment]
Mhh one thing I wasn't sure about: the tags from the repository are in the form of 0.1.2 but they are rewritten as v0, v0.1 and v0.1.2. Looks like all other projects have a 'v' prefix.

**Comment by michaelopdenacker** [comment]
Right, thanks.
I remember now that the 3rd fields in list-tags -h must match the git tags.
So the website looks good now.
Cheers

**Comment by mwalle** [comment]
cool, thanks!

**Pull request merged**
