### PR TITLE
Added an api, based on wsgi_mod with falcon framework

### PR DESCRIPTION
**Pull request by carmeli-tamir**
Implemented a JSON REST api for the 'ident' query.
The REST api is implemented using falcon framework, over mod_wsgi extension for httpd (apache).

I have added instructions in the README for how to install mod_wsgi and how to configure the .conf file in order to make it work. Tell me if you get in trouble, I'll help.

If this PR is merged, I intend to clean the code duplication in web.py and api.py regarding the initialization and usage of query, and also the implement the API for more queries as well.

### CODE REVIEW

**Comment by michaelopdenacker** [comment]
Accepted. Many thanks for all this work :)
I will try to enable it on the production website today, so that you can test this instance too.
Thanks again,
Michael.

**Comment by michaelopdenacker** [comment]
Hey, I've go trouble testing your new API...
curl http://elixir.bootlin.com/api/ident/barebox/cdev?version=latest

Here's what I get on the server logs:
[Tue Oct 15 20:02:44.900336 2019] [http:error] [pid 20399] [client 10.123.242.181:36146] AH02429: Response header name '<!--' contains invalid characters, aborting request

How would you debug this? How could I debug that from the server itself? I'm asking because elixir.bootlin.com uses a cache, which complicates things a little bit...

**Comment by carmeli-tamir** [comment]
Hi,
From googline a bit, please try the method described here:
https://stackoverflow.com/questions/45375693/apache2-response-header-name-contains-invalid-characters-aborting-reque

( cgitb.enable(display=0, logdir=OUTDIR) )

to see a more detailed error

**Comment by carmeli-tamir** [comment]
Maybe also attach the relevant sections in the httpd configuration if my previous message didn't help

**Comment by michaelopdenacker** [comment]
Thanks for the tip. I tried that before but didn't get any further output (though the trick worked once in the past... not sure why).

I eventually found the culprit: the second RewriteRule setting that caught the requests and redirected it to web.py:

RewriteRule "^/.*/(source|ident|search)" "/web.py" [PT]

I tried to add a rule to intercept the /api URLs first, but haven't succeeded yet to skip this rule:
        RewriteRule "^/$api.*" "/api.py" [L,PT]
        RewriteRule "^/.*/(source|ident|search)" "/web.py" [PT]

I have very little free time this week, so if you can propose something that could work, your help would be most appreciated :)

**Comment by carmeli-tamir** [comment]
I didn't use RewriteRule for /api, I just placed the WSGIScriptAlias above the other existing RewriteRules.

This is what my conf looks like (works on my test machine):

<Directory /home/osboxes/projects/elixir/http/>
    Options +ExecCGI
    AllowOverride None
    Require all granted
    SetEnv PYTHONIOENCODING utf-8
    SetEnv LXR_PROJ_DIR /home/osboxes/projects/elixir-proj/
</Directory>

<Directory /home/osboxes/projects/elixir/api/>
    SetHandler wsgi-script
    Require all granted
    SetEnv PYTHONIOENCODING utf-8
    SetEnv LXR_PROJ_DIR /home/osboxes/projects/elixir-proj/
</Directory>

WSGIPythonHome /home/osboxes/projects/elixir/env

AddHandler cgi-script .py
#Listen 80
<VirtualHost *:80>
    ServerName elixir
    DocumentRoot /home/osboxes/projects/elixir/http/
    RewriteEngine on

    WSGIScriptAlias /api /home/osboxes/projects/elixir/api/api.py

    RewriteRule "^/$" "/linux/latest/source" [R]
    RewriteRule "^/(?!api).*/(source|ident|search)" "/web.py" [PT]

    </VirtualHost>
        </IfDefine>
</IfModule>

**Comment by michaelopdenacker** [comment]
I also have WSGIScriptAlias before all RewriteRule lines.
See my current configuration (the link will expire in one month):
https://framabin.org/p/?5799b1e0d177d321#VcCabSCBg7iVmnLRUtfyZGQn6xyEVtehiGcvBTA7JTI=

A way to fix the issue and make the API interface work is to remove the second RewriteRule:
RewriteRule "^/(?!api).*/(source|ident|search)" "/web.py" [PT]

But of course it breaks the normal http interface for Elixir...

**Comment by carmeli-tamir** [comment]
This is exactly the line in which we differ, the configuration you currently have:
RewriteRule "^/.*/(source|ident|search)" "/web.py" [PT]

The configuration I tested has:
RewriteRule "^/(?!api).*/(source|ident|search)" "/web.py" [PT]

I changed the rule not to apply for uri's that don't start with api. When I test it both the API and the HTTP work. Probably this is the issue?

**Comment by carmeli-tamir** [comment]
I could also change the string ident to something else but I suspect that editing the existing RewriteRule as I've suggested will work out. Do update :)

**Comment by michaelopdenacker** [comment]
Hi,
Sorry for the delay, your proposed change worked.
Thanks a lot  :)
Many thanks !

BTW, let me know when you think we are ready to announce the new api. I was planning to make an announcement through a blog post celebrating version 1.0 and its new features :)

**Comment by carmeli-tamir** [comment]
Great :) 
Yep it's a good idea! I think you can go ahead at it. I was thinking of adding more API features like getting the versions of a project but I don't think it's a showstopper for an announcement (unless you think so)

**Pull request merged**
