### PR TITLE
Refactor query module into a class to avoid global state

### PR DESCRIPTION
**Pull request by fstachura**
Proposed fix to #269 

Refactors the query module into a class to avoid global state and allow for multiple concurrent instances (of the module)

### CODE REVIEW

**Comment by fstachura** [comment]
I dislike the fact that this patch makes changes to the whole python codebase. I'm going to try to limit major changes only to api.py, query.py

**Comment by tleb** [comment]
I've done a first read-through to facilitate work to get this merged. Keep in mind I'm not familiar with the codebase. Not many people are; it's a long-lived project that is not touched often.

**Comment by fstachura** [comment]
I marked this as WIP because I'm not satisfied with the tests I have done so far. 
I'm also not sure if this is the right approach. While I think that refactoring the python codebase to depend less on mutable global state is a good thing in the long term, there are probably "safer" ways to get around that API bug. For example, rewriting the API into a CGI script would work too, while being less complex than this change. 

I'm not confident about the environment variables used by script.sh (and its dependencies). Query class only stores (and passes to script.sh) environment variables that were modified by the API script. I also assumed that the env vars only matter to lib.py:script and scriptLines, but this could be incorrect.
The fact that default_query is instantiated on import is another problem, because that requires the LXR_DATA_DIR and LXR_REPO_DIR env vars to be set. I'm not really sure how to get around that without getting rid of the global query functions and refactoring the whole codebase that utilizes them to instantiate the Query class instead. Setting these vars to something valid in the API is hacky, but should work too.

**Comment by fstachura** [comment]
I have done a following test to 

https://gist.github.com/fstachura/f4a51f8e133825567c29c1a2e29032d3
`python3 crawl.py http://172.17.0.2/linux/latest/source/kernel/auditfilter.c & python3 crawl.py http://172.17.0.2/musl/latest/source/src/linux/xattr.c & python3 crawl.py http://172.17.0.2/u-boot/latest/source/fs/ext4/ext4_common.c`

In another tab:
`while true; do curl http://172.17.0.2/api/ident/musl/kstat\?version\=latest; echo; done`

On current master, it is likely that the second tab will sometimes (if not always) return empty responses. On this branch, the second tab should always return a valid response. 

However, I'm still unsure about memory leaks. So far, I was not able to confirm that the application actually leaks memory. Memory usage grows to some amount (higher than on master) and seems to hover around that. That still seems suspicious to me.

**Comment by fstachura** [comment]
A simple test to see that this behaves differently from current master - for each project, run
`while true; do curl http://172.17.0.2/api/ident/<project>/<identifier>\?version\=latest; echo; done`.

On current master, at least one such loop should sometimes return empty responses. On this branch, requests to api should always return valid (nonempty) responses for indexed identifiers.

However, I'm still unsure about memory leaks. So far, I was not able to confirm that the application actually leaks memory. Memory usage grows to some amount and then seems to hover around that. However, I was also unable to find an actual upper bound. After reaching a certain level, memory usage might appear to have stopped growing, but actually still grows, just rarely and very, very slowly (at least with my stress scripts). That still seems suspicious to me. 
The current master seems to behave in the same way, so if this is not a problem now, it probably shouldn't be a problem after this patch is applied. 
That said, I'm torn on rewriting the API as a CGI script - that would fix this issue, while also being safe against memory leaks.

**Comment by fstachura** [comment]
Hi @michaelopdenacker 

I think I have tested the code well enough (although there could still be something missing, like in the original PR). If you are OK with merging this PR and reverting it in case of issues, then I think that this is probably the best option.

If would suggest checking if the current version of the API (before this PR) does not leak memory. I don't mean any "active" tests - I hope that traces of that happening in the past should be visible in /var/log/apache2/error.log, dmesg or syslog. If it doesn't, then this patch probably shouldn't either. If it does, then still I think that this shouldn't make things much worse, but I will try to rewrite the API as a CGI script to fix the leaks.

**Comment by michaelopdenacker** [comment]
OK, thanks, let's try!

**Comment by michaelopdenacker** [comment]
image

@fstachura Loading the JS popup seems to be broken, but perhaps it's because of our http cache, not because of this change?
Disabling Javascript is a work-around.

**Comment by fstachura** [comment]
@michaelopdenacker I have a suspicion that this is because query requires the LXR_DATA_DIR and LXR_REPO_DIR environment variables to be set during the first import to instantiate the default query class, but api.py doesn't set them before the import. This works ok in the docker image, because the variables are set during the build phase. Could you try setting the LXR_DATA_DIR and LXR_REPO_DIR in apache config to any correct values? (linux for example)

**Comment by michaelopdenacker** [comment]
@fstachura Thanks for the quick answer!
I made the change that you suggested in the Apache config:
        SetEnv LXR_DATA_DIR path/elixir-data/linux/data
        SetEnv LXR_REPO_DIR <path>/elixir-data/linux/repo
        
 We already have:
        SetEnv LXR_PROJ_DIR path

However, it doesn't seem to help. Anyway, this was just for testing, right? As we support multiple projects, those variables should be project specific.

**Comment by michaelopdenacker** [comment]
Sure, I sent logs directly to you by e-mail. I prefer not to expose too many details about our server.
Thanks!

**Comment by fstachura** [comment]
Yeah, it looks that default_query construction fails. I'm no apache expert, but maybe the variables are in the wrong directive? 
https://github.com/bootlin/elixir/blob/master/docker/debian/000-default.conf#L8

My guess is that `<Directory /usr/local/elixir/api/>` would be the best option.

**Comment by michaelopdenacker** [comment]
FYI, if you're having such issues too with the latest code, we ended up using this quick fix:

Add the below lines to api/api.py before import query
os.environ["LXR_DATA_DIR"] = "/srv/elixir-data/linux/data"
os.environ["LXR_REPO_DIR"] = "/srv/elixir-data/linux/repo" 

(adapt to your exact paths on your server). This looks like specific to Linux but this is just so that  "default_query" gets instantiated.

**Pull request merged**
